const vocabulary = [
    "un", "Eins",
    "deux", "Zwei",
    "trois", "Drei",
    "quatre", "Vier",
    "cinq", "Fünf",
    "six", "Sechs",
    "sept", "Sieben",
    "huit", "Acht",
    "neuf", "Neun",
    "dix", "Zehn",
    "onze", "Elf",
    "douze", "Zwölf",
    "treize", "Dreizehn",
    "quatorze", "Vierzehn",
    "quinze", "Fünfzehn",
    "seize", "Sechzehn",
    "dix-sept", "Siebzehn",
    "dix-huit", "Achtzehn",
    "dix-neuf", "Neunzehn",
    "vingt", "Zwanzig",

    "Bienvenue", "Willkommen",
    "Bonjour", "Guten Tag",
    "je m'appelle", "Ich heiße",
    "moi", "ich",
    "c'est", "das ist",
    "Salut!", "Hallo!",
    "et", "und",
    "toi", "du",
    "comment", "wie",
    "Tu t'appelles comment?", "Wie heißt du?",
    "Ça va?", "Wie geht's?",
    "un bisou", "ein Küsschen",
    "merci", "danke",
    "À bientôt!", "Bis bald!",
    "oui", "ja",
    "à plus", "bis später!",
    "bien", "gut",
    "Ça va bien", "Es geht mir gut",
    "Au revoir!", "Auf Wiedersehen!",
    "voilà", "da ist/das ist, da sind /das sind",
    "Bonjour les amis!", "Guten Tag, Freunde!",
]
